---
resources:
  limits:
    cpu: "6"
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 64Mi
serviceAccount: log-collector
outputs:
  httpTimeout: 10
  insecureSkipVerify: false
  tuning:
    maxWrite: 1048576
  ca:
    configMap: custom-ca-bundle
    key: ca.crt
  application:
    url: https://default.main.stoic-gauss-qcj0f23.cribl.cloud:10080/cribl/_bulk
    secret:
      name: openshift-logging-bearer-tokens     # rhacm policy will create this secret
      key: application                          # with the application, infrastructure, and audit keys
  infrastructure:
    url: https://default.main.stoic-gauss-qcj0f23.cribl.cloud:10080/cribl/_bulk
    secret:
      name: openshift-logging-bearer-tokens
      key: infrastructure
  audit:
    url: https://default.main.stoic-gauss-qcj0f23.cribl.cloud:10080/cribl/_bulk
    secret:
      name: openshift-logging-bearer-tokens
      key: audit
...
