---
advertisementMode: bgp
ipAddressRanges:
  - 10.176.25.64/28
  - 10.13.113.1-10.13.113.10
bgp:
  myASN: 64513
  peerASN: 64513
  routerID: 10.118.10.13
  keepaliveTime: 30s
  holdTime: 90s
  passwordSecret: bgp-secret
  ebgpMultiHop: false
  aggregationLength: 30
  communities:
    - 65535:65281           # NO_EXPORT
    - 65535:65282           # NO_ADVERTISE
  peers:
    - peerAddress: 10.118.11.1
      peerPort: 179
    - peerAddress: 10.118.11.2
      peerPort: 179
...
