---
server:
  autoscale:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
rbac:
  defaultPolicy: "role:admin"
repo:
  replicas: 3
ha:
  enabled: true
redis:
  tls:
    customCA: "custom-ca.crt"
controller:
  sharding:
    enabled: true
    replicas: 3
    algorithm: consistent-hashing
disableAdmin: false
appProjects:
  - name: gitops
    sourceRepos:
      - "https://github.com/bkkhoo/argocd.git"
      - "https://github.com/bkkhoo/helm-values.git"
  - name: uat-dummy
    sourceRepos:
      - "*"
...
