---
server:
  autoscale:
    enabled: false
rbac:
  defaultPolicy: "role:admin"
repo:
  replicas: 1
redis:
  ha:
    enabled: false
controller:
  sharding:
    enabled: false
disableAdmin: false
appProjects:
  - name: iac-gitops
    sourceRepos:
      - "https://github.com/bkkhoo/*"

appProjects:
  - name: iac-gitops
    sourceRepos:
      - "https://github.com/bkkhoo/argocd.git"
      - "https://github.com/bkkhoo/helm-values.git"
  - name: dev-dummy
    sourceRepos:
      - "*"
...
